// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/_middleware.ts";
import * as $2 from "./routes/app/[id].tsx";
import * as $3 from "./routes/app/error.tsx";
import * as $4 from "./routes/category/[id].tsx";
import * as $5 from "./routes/category/index.tsx";
import * as $6 from "./routes/docs/[doc].tsx";
import * as $7 from "./routes/docs/index.tsx";
import * as $8 from "./routes/env.js.ts";
import * as $9 from "./routes/gfm.css.ts";
import * as $10 from "./routes/home.tsx";
import * as $11 from "./routes/index.tsx";
import * as $12 from "./routes/login.tsx";
import * as $13 from "./routes/loved.tsx";
import * as $14 from "./routes/offline.tsx";
import * as $15 from "./routes/privacy.tsx";
import * as $16 from "./routes/search.tsx";
import * as $17 from "./routes/settings.tsx";
import * as $18 from "./routes/sitemap.xml.ts";
import * as $19 from "./routes/terms-and-conditions.tsx";
import * as $$0 from "./islands/Dialog.tsx";
import * as $$1 from "./islands/InstallBanner.tsx";
import * as $$2 from "./islands/LoginButtons.tsx";
import * as $$3 from "./islands/LoginErrorDialog.tsx";
import * as $$4 from "./islands/LogoutButton.tsx";
import * as $$5 from "./islands/LoveAppButton.tsx";
import * as $$6 from "./islands/LovedApps.tsx";
import * as $$7 from "./islands/Navbar.tsx";
import * as $$8 from "./islands/UserHandler.tsx";

const manifest = {
	routes: {
		"./routes/_app.tsx": $0,
		"./routes/_middleware.ts": $1,
		"./routes/app/[id].tsx": $2,
		"./routes/app/error.tsx": $3,
		"./routes/category/[id].tsx": $4,
		"./routes/category/index.tsx": $5,
		"./routes/docs/[doc].tsx": $6,
		"./routes/docs/index.tsx": $7,
		"./routes/env.js.ts": $8,
		"./routes/gfm.css.ts": $9,
		"./routes/home.tsx": $10,
		"./routes/index.tsx": $11,
		"./routes/login.tsx": $12,
		"./routes/loved.tsx": $13,
		"./routes/offline.tsx": $14,
		"./routes/privacy.tsx": $15,
		"./routes/search.tsx": $16,
		"./routes/settings.tsx": $17,
		"./routes/sitemap.xml.ts": $18,
		"./routes/terms-and-conditions.tsx": $19,
	},
	islands: {
		"./islands/Dialog.tsx": $$0,
		"./islands/InstallBanner.tsx": $$1,
		"./islands/LoginButtons.tsx": $$2,
		"./islands/LoginErrorDialog.tsx": $$3,
		"./islands/LogoutButton.tsx": $$4,
		"./islands/LoveAppButton.tsx": $$5,
		"./islands/LovedApps.tsx": $$6,
		"./islands/Navbar.tsx": $$7,
		"./islands/UserHandler.tsx": $$8,
	},
	baseUrl: import.meta.url,
	config,
};

export default manifest;
